"""empty message

Revision ID: 45609f445125
Revises: 926311a2f128
Create Date: 2020-08-04 21:07:44.730846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45609f445125'
down_revision = '926311a2f128'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('genres', sa.String(length=120), nullable=True))
    op.add_column('venues', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'genres')
    op.drop_column('artists', 'genres')
    # ### end Alembic commands ###
