"""empty message

Revision ID: 926311a2f128
Revises: 574264d43b5c
Create Date: 2020-08-04 17:30:53.974577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '926311a2f128'
down_revision = '574264d43b5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'genres')
    # ### end Alembic commands ###
